apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mc-app-monitor
  namespace: prometheus
  labels:
    release: stable
spec:
  namespaceSelector:
    matchNames:
      - lab
  selector:
    matchLabels:
      app: mc-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s